name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"

permissions:
  contents: read
  actions: read

jobs:

    JDCloud-ImmortalWrt:
      uses: ./.github/workflows/JDCloud-ImmortalWrt.yml
      permissions:
        contents: write
        actions: write

    Build-Packages:
      uses: ./.github/workflows/Build-OpenWrt.yml
      permissions:
        contents: write
        actions: read

